### PR TITLE
Fix #3, and temporarily accept #2 as edge case

### LINKED ISSUE #3: Corner points are not removed
Sorry for the noise, I am not sure my comment to a closed issue will stay on the radar – for awareness’ sake, here it is again:

The fix to #2 breaks the non-interactive corner rounding in the following way:
https://www.dropbox.com/s/7p2g739i9vt5i1f/corner.mov?dl=0

### PR DESCRIPTION
**Pull request by ryanbugden**

### CODE REVIEW

**Comment by frankrolf** [comment]
Please merge this. #2 broke this extension for solving an edge case.

**Comment by typemytype** [comment]
does it fix #2 and #3? 

I dont have time to follow up and double check, but happy to merge it

**Comment by frankrolf** [comment]
#2 is a fix for a problem that’s not important. It’s theoretical.
#2 introduces a bug which is seen in every use of the extension.

**Comment by typemytype** [comment]
he fix I did back then was wrong anyhow...

maybe a check must happen so the list does not pop an index above the len of the point list.
I cannot reproduce the error from #2 anymore (possible fontParts vs roboFab) 

```python
startIndex = 4
points = [1, 2, 3, 4]

print(len(points), startIndex, len(points) > startIndex)
if len(points) > startIndex:
    r = points.pop(startIndex)
print(points)
```

**Pull request merged**
